apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: crypto-app
  labels:
    app: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      serviceAccountName: collector
      containers:
        - name: collector
          image: asia-northeast3-docker.pkg.dev/parkdh0121/crypto-vitals/collector:latest
          env:
            - name: BQ_PROJECT
              value: "parkdh0121"
            - name: BINANCE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: binance-secret
                  key: BINANCE_API_KEY
            - name: BINANCE_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: binance-secret
                  key: BINANCE_API_SECRET
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          imagePullPolicy: Always
